// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package client

import (
	"github.com/nuttchai/go-ddd/internal/core/http/routers"
	"github.com/nuttchai/go-ddd/internal/core/infra/data-mappers"
	"github.com/nuttchai/go-ddd/internal/di"
)

// Injectors from wire.go:

func InitializeHTTPServer() (*di.HTTPServer, func(), error) {
	echo := di.ProvideEcho()
	appConfig, err := di.ProvideAppConfig()
	if err != nil {
		return nil, nil, err
	}
	routerRouter := router.NewRouter()
	db, cleanup, err := di.ProvideDB(appConfig)
	if err != nil {
		return nil, nil, err
	}
	userDataMapper := data_mapper.NewUserDataMapper()
	userRepository, err := di.ProvideUserRepository(db, userDataMapper)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userUsecase, err := di.ProvideUserUsecase(userRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	envelopeBuilder := di.ProvideEnvelopeBuilder()
	userController, err := di.ProvideUserController(userUsecase, envelopeBuilder)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRoutesReady := di.RegisterUserRoutes(echo, routerRouter, userController)
	httpServer := di.ProvideHTTPServer(echo, appConfig, userRoutesReady)
	return httpServer, func() {
		cleanup()
	}, nil
}
